// Compiles the CashScript contracts into TypeScript artifacts under src/artifacts.
import { compileFile } from 'cashc';
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'src', 'artifacts');
mkdirSync(outDir, { recursive: true });

for (const name of ['GameOfLife', 'GameVault']) {
  const artifact = compileFile(join(root, 'contracts', `${name}.cash`));
  artifact.updatedAt = "1970-01-01T00:00:00.000Z"; // keep generated files stable
  const source = `// Generated by scripts/compile.mjs from contracts/${name}.cash - do not edit.\n`
    + `export default ${JSON.stringify(artifact, null, 2)} as const;\n`;
  writeFileSync(join(outDir, `${name}.ts`), source);
  console.log(`compiled ${name}: ${artifact.debug?.bytecode ? artifact.debug.bytecode.length / 2 : '?'} bytes`);
}
