// Generated by scripts/compile.mjs from contracts/GameVault.cash - do not edit.
export default {
  "contractName": "GameVault",
  "constructorInputs": [
    {
      "name": "stateCategory",
      "type": "bytes32"
    }
  ],
  "abi": [
    {
      "name": "absorb",
      "inputs": []
    }
  ],
  "bytecode": "OP_INPUTINDEX OP_0 OP_GREATERTHAN OP_VERIFY OP_0 OP_UTXOTOKENCATEGORY OP_SWAP OP_1 OP_CAT OP_EQUAL",
  "source": "pragma cashscript ^0.13.0;\n\n/*\n * GameVault - the funding address of a GameOfLife deployment.\n *\n * Anyone can send BCH here from any wallet. The coins can only be spent together with the\n * game's state NFT (always input 0), and the GameOfLife covenant carries every input's value\n * over into the game output, so vault coins can only ever pay for moves of the game.\n */\ncontract GameVault(bytes32 stateCategory) {\n    function absorb() {\n        require(this.activeInputIndex > 0);\n        require(tx.inputs[0].tokenCategory == stateCategory + 0x01);\n    }\n}\n",
  "fingerprint": "b105ff7673aca2a5425748f48ee33f69fd09baad18adfd6497692335459beab2",
  "debug": {
    "bytecode": "c000a06900ce7c517e87",
    "sourceMap": "12:16:12:37;:40::41;:16:::1;:8::43;13:26:13:27:0;:16::42:1;:46::59:0;:62::66;:46:::1;:8::68",
    "logs": [],
    "requires": [
      {
        "ip": 4,
        "line": 12
      },
      {
        "ip": 11,
        "line": 13
      }
    ]
  },
  "compiler": {
    "name": "cashc",
    "version": "0.13.3",
    "options": {
      "enforceFunctionParameterTypes": true,
      "enforceLocktimeGuard": true
    }
  },
  "updatedAt": "1970-01-01T00:00:00.000Z"
} as const;
